# Generated by Django 4.0.6 on 2022-08-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('location', models.CharField(max_length=254)),
                ('date', models.DateTimeField()),
                ('contact_info', models.CharField(blank=True, max_length=254)),
            ],
        ),
    ]
