# Generated by Django 4.0.6 on 2022-08-24 20:05

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=254)),
                ('cmc', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('card_img', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='card')),
                ('set', models.TextField(blank=True)),
                ('rarity', models.TextField(blank=True)),
                ('oracle_text', models.TextField(blank=True)),
                ('flavor_text', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.type')),
                ('user_favorite', models.ManyToManyField(blank=True, related_name='wishlist_item', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
