# Generated by Django 4.0.6 on 2022-08-03 16:08

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('color', cloudinary.models.CloudinaryField(max_length=255, verbose_name='mana_symbol')),
                ('oracle_text', models.CharField(blank=True, max_length=254)),
                ('flavor_text', models.CharField(blank=True, max_length=254)),
                ('set', models.CharField(max_length=254)),
                ('rarity', models.CharField(max_length=254)),
                ('cmc', models.DecimalField(blank=True, decimal_places=2, max_digits=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('version', models.CharField(blank=True, max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
