# Generated by Django 4.0.6 on 2022-08-25 18:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_card_card_img_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='color',
            new_name='type_line',
        ),
        migrations.RemoveField(
            model_name='card',
            name='rarity',
        ),
        migrations.RemoveField(
            model_name='card',
            name='set',
        ),
        migrations.RemoveField(
            model_name='card',
            name='type',
        ),
        migrations.AddField(
            model_name='card',
            name='colors',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='card',
            name='mana_cost',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='card',
            name='user_favorite',
            field=models.ManyToManyField(blank=True, related_name='user_favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
