# Generated by Django 4.0.6 on 2022-08-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_color_card_type_line_remove_card_rarity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='colors',
            field=models.JSONField(),
        ),
    ]
