# Generated by Django 4.0.6 on 2022-08-11 19:28

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_card_cmc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catergory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='card',
            name='version',
        ),
        migrations.AddField(
            model_name='card',
            name='card_img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='card'),
        ),
        migrations.AddField(
            model_name='card',
            name='card_img_url',
            field=models.URLField(blank=True, max_length=1024),
        ),
    ]
