# Generated by Django 4.0.6 on 2022-08-12 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_catergory_remove_card_version_card_card_img_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catergory',
            new_name='Type',
        ),
    ]
