# Generated by Django 4.0.6 on 2022-08-12 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_catergory_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.type'),
        ),
    ]
