# Generated by Django 4.0.6 on 2022-08-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_card_flavor_text_alter_card_oracle_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='rarity',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='set',
            field=models.TextField(),
        ),
    ]
