# Generated by Django 4.0.6 on 2022-08-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_card_rarity_alter_card_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='flavor_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='oracle_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='rarity',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='set',
            field=models.TextField(blank=True),
        ),
    ]
